### ISSUE TITLE
Players cannot click on the piece sprite itself to move a move to that square

### ISSUE THREAD

**Issue by gilllian** [gilllian/SE181#44]
Players can move a piece by:
1. Clicking on the piece they want to move
2. Click the square they want to move the piece to

On step 2, if the selected square already has a piece on it (an opponent piece and they want to capture it), the player must click on the square itself. If they click the piece, the move will not register.

**Comment by CyanPrinterInk** [comment]
Fixed under #62, this bug can be closed when #70 is merged to master.
